spring.datasource.url: jdbc:mysql://localhost:3306/taskstorage
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.hibernate.ddl-auto: none

greeting: What's cooking, good looking? ;)